# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  # config.ssh.username = 'gp2'
  # config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'
  # config.ssh.private_key_path = '~/.ssh/id_rsa'
end
