# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network :forwarded_port, guest: 8080, host: 9080
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.inventory_file = "ansible/dev"
  end
  # config.ssh.username = 'gp2'
  # config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'
  # config.ssh.private_key_path = '~/.ssh/id_rsa'
end
