# -*- mode: ruby -*-
# vi: set ft=ruby :

def f(path)
  File.dirname(__FILE__) + "/" + path
end

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network :forwarded_port, guest: 8080, host: 8081
  config.vm.network :forwarded_port, guest: 80, host: 8082
  config.vm.provision :ansible do |ansible|
    ansible.playbook = f "ansible/provision.yml"
    ansible.inventory_file = f "ansible/dev"
  end
  # config.ssh.username = 'gp2'
  # config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'
  # config.ssh.private_key_path = '~/.ssh/id_rsa'
end
